# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import migration_control.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', migration_control.db.models.CharField(max_length=50)),
            ],
        ),
    ]
